---
title: "PY795 Presentation"
subtitle: "Yes, I did this on RStudio; <br/> Yes, I am sorry"
author: 
institute: 
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---